### PR TITLE
Mujahed

### PR DESCRIPTION
**Pull request by Mohd-Mujahed**

### CODE REVIEW

**Review by Mohd-Mujahed — COMMENTED** [review]
Approve it

**Review by abdulvasay-234 — APPROVED** [review]
@Mohd-Mujahed can you resolve the conflicts

**Review by abdulvasay-234 — CHANGES_REQUESTED** [review]
Resolve the conflict in the code

**Review by abdulvasay-234 — APPROVED** [review]
LGTM

**Pull request merged**
